engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- server/tests/**/*
